var main_trials = [
	{question: "How does this cat look?", 
	 option1: "cute", 
	 option2: "ugly", 
	 option3: "scary",
	 picture: "images/catpics/cc1.jpeg"},
	{question: "How does this cat look?", 
	 option1: "cute", 
	 option2: "ugly", 
	 option3: "scary",
	 picture: "images/catpics/cc2.jpeg"},
	 {question: "How does this cat look?", 
	 option1: "cute", 
	 option2: "ugly", 
	 option3: "scary",
	 picture: "images/catpics/cc3.jpeg"},
	 {question: "How does this cat look?", 
	 option1: "cute", 
	 option2: "ugly", 
	 option3: "scary",
	 picture: "images/catpics/cc4.jpeg"},
	 {question: "How does this cat look?", 
	 option1: "cute", 
	 option2: "ugly", 
	 option3: "scary",
	 picture: "images/catpics/cc5.jpeg"},
	 {question: "How does this cat look?", 
	 option1: "cute", 
	 option2: "ugly", 
	 option3: "scary",
	 picture: "images/catpics/uc1.jpeg"},
	 {question: "How does this cat look?", 
	 option1: "cute", 
	 option2: "ugly", 
	 option3: "scary",
	 picture: "images/catpics/uc2.jpeg"},
	 {question: "How does this cat look?", 
	 option1: "cute", 
	 option2: "ugly", 
	 option3: "scary",
	 picture: "images/catpics/uc3.jpeg"},
	 {question: "How does this cat look?", 
	 option1: "cute", 
	 option2: "ugly", 
	 option3: "scary",
	 picture: "images/catpics/uc4.jpeg"},
	 {question: "How does this cat look?", 
	 option1: "cute", 
	 option2: "ugly", 
	 option3: "scary",
	 picture: "images/catpics/uc5.jpeg"},
];